"""
Agent state definition for the LangGraph multi-agent bug-fixing loop.
Uses TypedDict for LangGraph state compatibility.
"""

from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict


class AgentState(TypedDict, total=False):
    """Stateful context that flows through every agent node."""

    # ── Input ──────────────────────────────────────────────────────────
    bug_report: Optional[str]
    """Human-written bug report (if reactive mode)."""
    
    ci_failure_log: Optional[str]
    """Raw stderr/stdout from a failed CI run (if proactive mode)."""
    
    git_diff: Optional[str]
    """Diff of what the developer just pushed (if proactive mode)."""
    
    repo_path: str
    test_command: str

    # ── Auditor ────────────────────────────────────────────────────────
    auditor_found_bug: bool
    """Did the Auditor detect a silent logic bug?"""
    auditor_report: str
    """Explanation of the silent logic bug."""
    generated_test_code: str
    """The pytest code generated by the Auditor to reproduce the bug."""

    # ── Manager ────────────────────────────────────────────────────────
    analysis: Dict[str, Any]
    """Structured bug analysis (error_type, suspected_files, etc)."""

    # ── Researcher ─────────────────────────────────────────────────────
    relevant_code: List[Dict[str, Any]]
    similar_fixes: List[Dict[str, Any]]
    strategy_document: str
    """Concise plan created by the Researcher for the Coder."""

    # ── Coder ──────────────────────────────────────────────────────────
    proposed_fix: Dict[str, str]
    """Mapping of file_path -> new_file_content."""
    proposed_patches: List[Dict[str, str]]
    """List of patches. Each patch has file_path, search_text, replace_text."""
    fix_explanation: str

    # ── Reviewer ───────────────────────────────────────────────────────
    reviewer_approved: bool
    """Did the Reviewer agent approve the code?"""
    reviewer_feedback: str
    """Critique from the Reviewer if the code was rejected."""
    risk_level: str
    """Risk level of the fix (LOW or HIGH), determined by the Reviewer."""

    # ── Sandbox ────────────────────────────────────────────────────────
    test_result: Dict[str, Any]
    """exit_code, stdout, stderr, duration_ms, timed_out"""

    # ── Error Analyzer ─────────────────────────────────────────────────
    error_analysis: str
    """Human-readable diagnosis of test failures for the Coder."""

    # ── Control Flow & Internal ────────────────────────────────────────
    iteration: int
    """Current retry attempt (starts at 0)."""
    max_iterations: int
    status: str
    """'in_progress', 'success', 'failed'"""
    error_log: List[str]

    _sandbox_path: Optional[str]
    _indexer: Any
